import { createStorybookPreview } from '@atlasng/internal/storybook';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - Generated by compodoc
import docJson from './compodoc/documentation.json';

const preview = createStorybookPreview({ docJson });

export default preview;
