import { createStorybookPreview } from '@atlasng/internal/storybook';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - Generated by compodoc
import docJson from './compodoc/documentation.json';

export default {
  ...createStorybookPreview({ docJson }),
  // NOTE: `tags` must be defined inline
  tags: ['autodocs'],
};
