import { setCompodocJson } from '@storybook/addon-docs/angular';
import { withThemeByClassName } from '@storybook/addon-themes';
import type { Preview } from '@storybook/angular';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - Generated by compodoc
import docJson from './compodoc/documentation.json';

const preview: Preview = {
  tags: ['autodocs'],
  decorators: [
    withThemeByClassName({
      themes: {
        'CNS Light': 'cns-light-theme',
        'CNS Dark': 'cns-dark-theme',
        'HRA Light': 'hra-light-theme',
        'HRA Dark': 'hra-dark-theme',
        'WPP Light': 'wpp-light-theme',
        'WPP Dark': 'wpp-dark-theme',
      },
      defaultTheme: 'HRA Light',
    }),
  ],
};

if (docJson) {
  setCompodocJson(docJson);
}

export default preview;
